# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 07:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Level2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Level1')),
            ],
        ),
        migrations.CreateModel(
            name='Level3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Level2')),
            ],
        ),
    ]
